spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size  : 100
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 20
logging.level:
  org.hibernate.SQL: debug
