spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/backmin
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size  : 100
  data:
    web:
      pageable:
        default-page-size: 20
logging.level:
  org.hibernate.SQL: debug
